llms:
  akash:
    akash_key: "sk-wsSXBy9BTQgVlWzdba2HDw"
    akash_base_url: "https://chatapi.akash.network/api/v1"
    akash_model: "DeepSeek-R1-Distill-Qwen-32B"
  ollama:
    is_enabled: false
tools:
  searxng:
    host: "http://localhost:8080"
  firecrawl:
    host: "http://localhost:9090"
