llms:
  akash:
    openai_api_key: "sk-wsSXBy9BTQgVlWzdba2HDw"
    openai_api_base: "https://chatapi.akash.network/api/v1"
    temperature: 0
    # availablie models: DeepSeek-R1 DeepSeek-R1-Distill-Llama-70B 
    # DeepSeek-R1-Distill-Qwen-14B DeepSeek-R1-Distill-Qwen-32B Meta-Llama-3-1-8B-Instruct-FP8 
    # Meta-Llama-3-1-405B-Instruct-FP8 Meta-Llama-3-2-3B-Instruct Meta-Llama-3-3-70B-Instruct
    model_name: "Meta-Llama-3-2-3B-Instruct"  
  ollama:
    base_url: "http://jek:11434"
    model: "llama3.2:3b"
    temperature: 0

agents:
  market_sentiment:
    llm: "akash"
    uses:
      - search_web
      - search_news
  probability_assistance:
    llm: "akash"
  technical_analyst:
    llm: "akash"
  trading_strategist:
    llm: "akash"

# tools:
#   searxng:
#     host: "http://localhost:8080"
#   firecrawl:
#     api_key: "test_key"
#     url: "http://localhost:9090"
#   alpha_vantage:
#     api_key: ""
